# Generated by Django 5.2.2 on 2025-06-10 10:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('satisfaction', models.BooleanField(blank=True, default=None, null=True)),
                ('delai_recommandation', models.IntegerField(blank=True, null=True, verbose_name='Délai avant première recommandation (secondes)')),
            ],
        ),
        migrations.CreateModel(
            name='Enseigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('secteur_activite', models.CharField(max_length=100)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('identifiant', models.CharField(max_length=100, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('client', 'Client')], default='client', max_length=50, verbose_name='Rôle')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('actif', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=10, verbose_name='Langue préférée')),
                ('recoit_notifications', models.BooleanField(default=True, verbose_name='Recevoir des notifications')),
                ('theme_sombre', models.BooleanField(default=False, verbose_name='Thème sombre activé')),
                ('premiere_connexion', models.BooleanField(default=True, verbose_name='Première connexion')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='Groupes auxquels ce compte appartient.', related_name='comptes', related_query_name='compte', to='auth.group', verbose_name='Groupes')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permissions spécifiques pour ce compte.', related_name='comptes', related_query_name='compte', to='auth.permission', verbose_name='Permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du magasin')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('code_postale', models.CharField(max_length=20, verbose_name='Code postal')),
                ('pays', models.CharField(max_length=50, verbose_name='Pays')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('enseigne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liasec_models.enseigne', verbose_name='Enseigne')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_pdf', models.FileField(upload_to='factures_pdfs/', verbose_name='Fichier PDF')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('payee', models.BooleanField(default=False, verbose_name='Facture payée')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liasec_models.magasin', verbose_name='Magasin concerné')),
            ],
            options={
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='CompteEnseigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('date_lien', models.DateTimeField(auto_now_add=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liasec_models.compte')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liasec_models.magasin')),
            ],
        ),
        migrations.CreateModel(
            name='Borne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('etat', models.CharField(choices=[('en ligne', 'En ligne'), ('hors ligne', 'Hors ligne')], default='en ligne', max_length=20)),
                ('date_installation', models.DateTimeField(auto_now_add=True)),
                ('derniere_connexion', models.DateTimeField(auto_now=True)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liasec_models.magasin')),
            ],
        ),
        migrations.CreateModel(
            name='Messagerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pour_tous_admins', models.BooleanField(default=False, verbose_name='Visible par tous les admins')),
                ('titre', models.CharField(max_length=255, verbose_name='Objet de la discussion')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dernière activité')),
                ('est_lu_par_client', models.BooleanField(default=False, verbose_name='Lu par le client')),
                ('est_lu_par_admin', models.BooleanField(default=False, verbose_name="Lu par l'administrateur")),
                ('supprime_par_admin', models.BooleanField(default=False, verbose_name='Supprimée côté admin')),
                ('supprime_par_client', models.BooleanField(default=False, verbose_name='Supprimée côté client')),
                ('archived', models.BooleanField(default=False, verbose_name='Archivée')),
                ('expediteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messageries_envoyees', to='liasec_models.compte', verbose_name='Expéditeur')),
                ('magasin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_magasin', to='liasec_models.magasin', verbose_name='Magasin concerné')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='MessageChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Message')),
                ('date_envoi', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'envoi")),
                ('visible_par_admin', models.BooleanField(default=True, verbose_name='Visible côté admin')),
                ('visible_par_client', models.BooleanField(default=True, verbose_name='Visible côté client')),
                ('lu_par_admin', models.BooleanField(default=False, verbose_name="Lu par l'administrateur")),
                ('lu_par_client', models.BooleanField(default=False, verbose_name='Lu par le client')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liasec_models.compte', verbose_name='Auteur')),
                ('messagerie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='liasec_models.messagerie', verbose_name='Messagerie liée')),
            ],
            options={
                'verbose_name': 'Message de chat',
                'verbose_name_plural': 'Messages de chat',
                'ordering': ['date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Contenu')),
                ('est_lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='liasec_models.compte', verbose_name='Compte concerné')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du produit')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('categorie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Catégorie')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('reference_interne', models.CharField(max_length=100, unique=True, verbose_name='Référence interne')),
                ('disponibilite', models.BooleanField(default=True, verbose_name='Disponible')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Image (URL)')),
                ('marque', models.CharField(blank=True, max_length=255, null=True)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='liasec_models.magasin', verbose_name='Magasin')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(choices=[('client', 'Client'), ('ia', 'IA')], max_length=10)),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('is_recommandation', models.BooleanField(default=False)),
                ('satisfaction', models.BooleanField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='liasec_models.conversation')),
                ('produit_recommande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='liasec_models.produit')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='produits_recommandes',
            field=models.ManyToManyField(blank=True, to='liasec_models.produit'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('borne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liasec_models.borne')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liasec_models.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liasec_models.session'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liasec_models.produit')),
            ],
        ),
        migrations.CreateModel(
            name='TacheClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=255)),
                ('est_faite', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('compte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liasec_models.compte')),
                ('magasin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liasec_models.magasin')),
            ],
        ),
    ]
