# Generated by Django 5.1.6 on 2025-06-16 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liasec_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compte',
            name='derniere_visite_notifications',
        ),
    ]
