# Generated by Django 5.1.6 on 2025-06-17 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liasec_models', '0002_compte_derniere_visite_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='magasin_cible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liasec_models.magasin', verbose_name='Visible pour tous les clients de ce magasin'),
        ),
        migrations.AddField(
            model_name='notification',
            name='pour_tous_admins',
            field=models.BooleanField(default=False, verbose_name='Visible par tous les admins'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='compte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='liasec_models.compte', verbose_name='Compte concerné'),
        ),
    ]
